# fly.toml app configuration file generated for palash-blog-backend on 2023-09-05T20:12:04-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "palash-blog-backend"
primary_region = "jnb"

[build]

[http_service]
  internal_port = 3011
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
